// Types
export type {
  Timestamps,
  SoftDelete,
  Pagination,
  PaginationParams,
  SortDirection,
  SortOrder,
  ApiResponse,
  ApiError,
  ApiResult,
  User,
  UserRole,
  UserProfile,
  Workspace,
  WorkspaceMember,
  Project,
  ProjectStatus,
  ProjectMember,
  ProjectMemberRole,
  Task,
  TaskStatus,
  TaskPriority,
  TaskType,
  SubTask,
  Comment,
  Label,
  Attachment,
  Activity,
  ActivityType,
  Notification,
  NotificationType,
} from "./types/index";

// Schemas
export {
  loginSchema,
  registerSchema,
  forgotPasswordSchema,
  resetPasswordSchema,
  createUserSchema,
  updateUserSchema,
  updateProfileSchema,
  changePasswordSchema,
  createWorkspaceSchema,
  updateWorkspaceSchema,
  inviteMemberSchema,
  updateMemberRoleSchema,
  createProjectSchema,
  updateProjectSchema,
  createTaskSchema,
  updateTaskSchema,
  moveTaskSchema,
  filterTasksSchema,
  createCommentSchema,
  updateCommentSchema,
  createLabelSchema,
  updateLabelSchema,
} from "./schemas/index";

export type {
  LoginInput,
  RegisterInput,
  ForgotPasswordInput,
  ResetPasswordInput,
  CreateUserInput,
  UpdateUserInput,
  UpdateProfileInput,
  ChangePasswordInput,
  CreateWorkspaceInput,
  UpdateWorkspaceInput,
  InviteMemberInput,
  UpdateMemberRoleInput,
  CreateProjectInput,
  UpdateProjectInput,
  CreateTaskInput,
  UpdateTaskInput,
  MoveTaskInput,
  FilterTasksInput,
  CreateCommentInput,
  UpdateCommentInput,
  CreateLabelInput,
  UpdateLabelInput,
} from "./schemas/index";

// Constants
export {
  TASK_STATUSES,
  TASK_STATUS_LABELS,
  TASK_PRIORITIES,
  TASK_PRIORITY_LABELS,
  TASK_PRIORITY_ORDER,
  TASK_TYPES,
  TASK_TYPE_LABELS,
  PROJECT_STATUSES,
  PROJECT_STATUS_LABELS,
  DEFAULT_PAGE_SIZE,
  MAX_PAGE_SIZE,
  MIN_PAGE_SIZE,
  RATE_LIMIT_WINDOW_MS,
  RATE_LIMIT_MAX_REQUESTS,
  RATE_LIMIT_AUTH_MAX_REQUESTS,
  MAX_FILE_SIZE,
  MAX_AVATAR_SIZE,
  MAX_ATTACHMENTS_PER_TASK,
  ALLOWED_IMAGE_TYPES,
  ALLOWED_FILE_TYPES,
  MAX_TASK_TITLE_LENGTH,
  MAX_TASK_DESCRIPTION_LENGTH,
  MAX_COMMENT_LENGTH,
  MAX_PROJECT_NAME_LENGTH,
  MAX_WORKSPACE_NAME_LENGTH,
  MAX_LABEL_NAME_LENGTH,
  MAX_USER_NAME_LENGTH,
  MAX_BIO_LENGTH,
  MAX_LABELS_PER_TASK,
  MAX_SUBTASKS_PER_TASK,
  MAX_PROJECTS_PER_WORKSPACE,
  MAX_MEMBERS_PER_WORKSPACE,
  LABEL_COLORS,
  PRIORITY_COLORS,
  PROJECT_COLORS,
  STATUS_COLORS,
} from "./constants/index";

// Utils
export {
  generateId,
  generatePrefixedId,
  createUserId,
  createWorkspaceId,
  createProjectId,
  createTaskId,
  createCommentId,
  createLabelId,
  createAttachmentId,
  createNotificationId,
  createActivityId,
  formatRelativeTime,
  formatISODate,
  formatDisplayDate,
  isOverdue,
  isDueSoon,
  nowISO,
  slugify,
  truncate,
  getInitials,
  capitalize,
  toTitleCase,
} from "./utils/index";
